Feature/evolution starter
esgiprojetninja/ninjaPokedex pull request #18
Opened 2017-06-29 12:27 UTC by teddymeksavanh

2017-06-29 14:43 UTC, dydyFos commented on public/css/card.css
> +.pokemon-current{
please tell me why it's empty

2017-06-29 14:44 UTC, teddymeksavanh commented on public/css/card.css
> +.pokemon-current{
parceque je vais mettre du css après, la le css est basique

2017-06-29 14:45 UTC, teddymeksavanh commented on public/css/card.css
> +.pokemon-current{
jvalide la fonctionnalitée plus

2017-06-29 14:46 UTC, dydyFos commented on public/js/lib/pokedex/ui/Carousel.js
> +                            for(var i = 0; i < this.props.pokemons.all.length; i++) {
.filter stp c'est qd mm bcp plus lisible

2017-06-29 14:47 UTC, teddymeksavanh commented on public/js/lib/pokedex/ui/Carousel.js
> +                            for(var i = 0; i < this.props.pokemons.all.length; i++) {
c'est plus rapide la boucle for, c'est plus de la perf

2017-06-29 14:48 UTC, teddymeksavanh commented on public/js/lib/pokedex/ui/Carousel.js
> +                            for(var i = 0; i < this.props.pokemons.all.length; i++) {
je met en .filter?

2017-06-29 14:52 UTC, dydyF05 requested changes

2017-06-29 14:52 UTC, dydyFos commented on public/js/lib/pokedex/ui/Carousel.js
> +                            for(var i = 0; i < this.props.pokemons.all.length; i++) {
D'ailleurs, savoir si un pokemon est une évolution d'un autre et inversement c'est de la data. Ça devrait se faire dans le reducer

2017-06-29 14:52 UTC, dydyFos commented on public/js/lib/pokedex/ui/Carousel.js
> +                            for(var j = 0; j < this.props.pokemons.all.length; j++) {
filter et mm pb. Mec y a deux appels d'une même action dans un touchtap. On peut améliorer ça ?

2017-06-29 14:52 UTC, dydyFos commented on public/js/lib/pokedex/ui/Home.js
>        return (
indent

2017-06-29 14:52 UTC, dydyFos commented on public/js/lib/pokedex/ui/Home.js
>        if( this.props.navbar.showSearch ) {
indent

2017-06-29 14:52 UTC, dydyFos commented on public/js/lib/pokedex/ui/Home.js
>        return (
indent

2017-06-29 14:52 UTC, dydyFos commented on public/js/lib/pokedex/ui/Home.js
> +    renderHomeCarousel () {
Jusqu'à présent on déclarait une fonction telle que : ma_fonction() {}. Maintenant tu fais ma_fonction () {}. Reason?

2017-06-29 14:52 UTC, dydyFos commented on public/js/lib/pokedex/ui/Home.js
>          <Row className="show-grid" style={{height: '50vh'}}>
indent

2017-06-29 14:52 UTC, dydyFos commented on public/js/lib/pokedex/ui/Home.js
>        if( this.props.home.showCarousel ) {
indent

2017-06-29 14:52 UTC, dydyFos commented on public/js/lib/pokedex/ui/Home.js
>          return this.renderHomeTable();
indent

2017-06-29 14:52 UTC, dydyFos commented on public/js/lib/pokedex/ui/Table.js
> +                        for(var i = 0; i < this.props.pokemons.all.length; i++) {
.filter

2017-06-29 14:52 UTC, dydyFos commented on public/js/lib/pokedex/ui/Table.js
> +                        for(var j = 0; j < this.props.pokemons.all.length; j++) {
.filter

2017-06-29 14:52 UTC, dydyFos commented on public/js/lib/pokedex/ui/Table.js
> +                        this.props.setSelectedPokemonForDetails(pokemon);
Je peux pas laisser merge une data qui est modifiée côté UI. Ça va à l'encontre de tout ce que j'ai appris en redux et en gestion de state

2017-06-29 14:54 UTC, dydyFos commented on public/js/lib/pokedex/ui/Carousel.js
> +                            for(var i = 0; i < this.props.pokemons.all.length; i++) {
for natif c'est plus rapide de 1 millionième de micro-seconde, c'est pertinent sur des tableaux de 3Mb. Avec nos 151 pov' pokemon franchement on a rien à craindre

2017-06-29 14:56 UTC, teddymeksavanh commented on public/js/lib/pokedex/ui/Table.js
> +                        this.props.setSelectedPokemonForDetails(pokemon);
Container :     
        setSelectedPokemonForDetails(pokemon) {
            dispatch(setSelectedPokemonForDetails(pokemon));
        },

Reducer : 

const initialSate = {
    showDetails: false,
    selectedPokemonForDetails: {}
};

    case types.SELECT_POKEMON:
            return {
                ...state,
                selectedPokemonForDetails: action.pokemon || {}
            }

J'ai pas compris ta remarque

2017-06-29 14:57 UTC, dydyFos commented on public/js/lib/pokedex/ui/Table.js
> +                        this.props.setSelectedPokemonForDetails(pokemon);
Tu crées de la data en modifiant celle déjà existante. Tu

2017-06-29 15:10 UTC, dydyFos commented on public/js/lib/pokedex/ui/Table.js
> +                        this.props.setSelectedPokemonForDetails(pokemon);
Et jusque là on s'en fout un peu

2017-06-29 15:10 UTC, dydyFos commented on public/js/lib/pokedex/ui/Table.js
> +                        this.props.setSelectedPokemonForDetails(pokemon);
Sauf que tu rajoutes des propriétés à cette référence avant de signifier à une action que tu as déjà modifié une data

2017-06-29 15:14 UTC, dydyFos commented on public/js/lib/pokedex/ui/Table.js
> +                        this.props.setSelectedPokemonForDetails(pokemon);
Si le but est de récupérer les évolutions : on peut p-e imaginer retrouver les évolutions du pokemon lorsque pokemon.getAll a reçu la réponse du serveur.

2017-06-30 15:15 UTC, dydyFos commented on public/js/lib/pokedex/ui/Carousel.js
> +                            function getStarter(el) {
à bouger

2017-06-30 15:15 UTC, dydyFos commented on public/js/lib/pokedex/ui/Carousel.js
> +                            function getEvolution(el, i) {
à bouger

2017-06-30 15:15 UTC, dydyFos commented on public/js/lib/pokedex/ui/Carousel.js
> +                            this.props.pokemons.all.filter(getStarter);
pull master

2017-06-30 15:15 UTC, dydyFos commented on public/js/lib/pokedex/ui/Carousel.js
> +                            this.props.pokemons.all.filter(getEvolution);
pull master stp

2017-06-30 15:18 UTC, dydyF05 requested changes

2017-06-30 15:18 UTC, dydyFos commented on public/js/lib/pokedex/ui/Home.js
> +                            // let pokemon = {};
ah

2017-06-30 15:18 UTC, dydyFos commented on public/js/lib/pokedex/ui/Home.js
> +                        // let pokemon = {};
teddybite

2017-07-07 10:31 UTC, dydyFos commented
s'passe quoi ici ?

2017-07-08 10:47 UTC, closed without merging